name: report-sys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dateutil
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - sqlalchemy==2.0.23
    - psycopg2-binary==2.9.9
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - python-multipart==0.0.6
    - alembic==1.12.1
    - python-dotenv==1.0.0
    - pydantic==2.5.2
    - pydantic-settings==2.1.0
    - python-slugify==8.0.1
    - pillow==10.1.0
    - email-validator==2.1.0.post1
