"""consolidate_models

Revision ID: e2273bbe30dc
Revises: d667f7272deb
Create Date: 2025-01-06 16:50:47.718649+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2273bbe30dc'
down_revision = 'd667f7272deb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
