"""fix_user_projects_table

Revision ID: 0d42cf9c81ec
Revises: da5f963f4dbb
Create Date: 2025-01-06 16:37:05.036187+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d42cf9c81ec'
down_revision = 'da5f963f4dbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attachments_id', table_name='attachments')
    op.drop_table('attachments')
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reports', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user_projects', 'project',
               existing_type=postgresql.ENUM('HIMS', 'ISPK', 'RASUMI', 'MDI', 'EROSES', 'MYASSESSMENT', 'MYCUKAI', name='project'),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_user_projects_id'), 'user_projects', ['id'], unique=False)
    op.drop_constraint('user_projects_user_id_fkey', 'user_projects', type_='foreignkey')
    op.create_foreign_key(None, 'user_projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.create_foreign_key('user_projects_user_id_fkey', 'user_projects', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_projects_id'), table_name='user_projects')
    op.alter_column('user_projects', 'project',
               existing_type=sa.String(),
               type_=postgresql.ENUM('HIMS', 'ISPK', 'RASUMI', 'MDI', 'EROSES', 'MYASSESSMENT', 'MYCUKAI', name='project'),
               nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reports', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('reports', 'updated_at')
    op.alter_column('comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name='attachments_report_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attachments_pkey')
    )
    op.create_index('ix_attachments_id', 'attachments', ['id'], unique=False)
    # ### end Alembic commands ###
