"""add_reports_and_attachments_tables

Revision ID: 3f24fd29df73
Revises: f0c67d04546f
Create Date: 2025-01-02 13:43:53.724185+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f24fd29df73'
down_revision = 'f0c67d04546f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
